version: "3.8"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma123
      POSTGRES_DB: deporder
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
